# spring:
#   application:
#     name: gateway
#   cloud:
#     gateway:
#       routes:
#         - id: user-service
#           uri: lb://USER-SERVICE
#           predicates:
#             - Path=/api/users/**


spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/