server:
  port: 8083

spring:
  application:
    name: ai-service

  data:
        mongodb:
            uri: mongodb://localhost:27017/Fitness_Activity
            database: Fitness_Activity

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest    

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key : activity.tracking                
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    

