spring:
  application:
    name: eureka

server:
    port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  instance:
    hostname: thurunu-ym
    nonSecurePort: ${server.port}
    preferIpAddress: false